// `npm run tokens` (step 1 of 2): tokens/ (W3C DTCG JSON) → Style Dictionary →
//   src/design-system/tokens/generated/*.ts   typed React Native theme
//   src/design-system/tokens/generated/tokens.css   CSS variables for web, same source
//   src/design-system/tokens/generated/themes.json  every scheme × accent, read by check-contrast
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

import * as prettier from 'prettier';
import StyleDictionary from 'style-dictionary';

const OUT = 'src/design-system/tokens/generated';
const SCHEMES = ['light', 'dark'];
const ACCENTS = ['care', 'plum', 'seaGlass'];
const DEFAULT_ACCENT = 'care';
const HEADER =
  '// Generated by scripts/build-tokens.mjs from tokens/. Do not edit by hand; run `npm run tokens`.\n';

const typeOf = (token) => token.$type ?? token.type;
const valueOf = (token) => token.$value ?? token.value;

// React Native transforms. RN sizes are unitless numbers, font weights are string literals,
// and RN 0.76+ (and react-native-web) take a CSS-style boxShadow string on every platform.
StyleDictionary.registerTransform({
  name: 'rn/dimension',
  type: 'value',
  filter: (token) => typeOf(token) === 'dimension',
  transform: (token) => parseFloat(String(valueOf(token))),
});
StyleDictionary.registerTransform({
  name: 'rn/fontWeight',
  type: 'value',
  filter: (token) => typeOf(token) === 'fontWeight',
  transform: (token) => String(valueOf(token)),
});
StyleDictionary.registerTransform({
  name: 'rn/shadow',
  type: 'value',
  filter: (token) => typeOf(token) === 'shadow',
  transform: (token) => {
    const { offsetX, offsetY, blur, spread, color } = valueOf(token);
    return `${offsetX} ${offsetY} ${blur} ${spread} ${color}`;
  },
});

const ACCENT_KEYS = ['accent', 'accentHover', 'accentActive', 'borderFocus'];

function dictionaryFor(scheme, accent, cssSelector, cssFilter) {
  return new StyleDictionary({
    source: [
      'tokens/primitive/*.json',
      `tokens/accent/${accent}.json`,
      `tokens/semantic/${scheme}.json`,
    ],
    usesDtcg: true,
    log: { verbosity: 'silent', warnings: 'disabled' },
    platforms: {
      rn: { transforms: ['rn/dimension', 'rn/fontWeight', 'rn/shadow'] },
      css: {
        transformGroup: 'css',
        prefix: 'dk',
        files: [
          {
            destination: 'tokens.css',
            format: 'css/variables',
            filter: cssFilter,
            options: { selector: cssSelector, outputReferences: false, showFileHeader: false },
          },
        ],
      },
    },
  });
}

/** Rebuild a nested plain object from Style Dictionary's flat token list. */
function toTree(allTokens, rootKey) {
  const tree = {};
  for (const token of allTokens) {
    if (token.path[0] !== rootKey) continue;
    let node = tree;
    const rest = token.path.slice(1);
    rest.forEach((key, i) => {
      if (i === rest.length - 1) node[key] = valueOf(token);
      else node = node[key] ??= {};
    });
  }
  return tree;
}

const colorsByCombo = {};
const cssBlocks = [];
let base;
let palette;

for (const scheme of SCHEMES) {
  for (const accent of ACCENTS) {
    const isDefault = accent === DEFAULT_ACCENT;
    const selector = isDefault
      ? scheme === 'light'
        ? ':root'
        : '[data-theme="dark"]'
      : scheme === 'light'
        ? `[data-accent="${accent}"]`
        : `[data-theme="dark"][data-accent="${accent}"]`;
    // :root carries everything; the other blocks carry only what they change.
    const cssFilter =
      isDefault && scheme === 'light'
        ? undefined
        : isDefault
          ? (token) => token.path[0] === 'color'
          : (token) => token.path[0] === 'color' && ACCENT_KEYS.includes(token.path[1]);

    const sd = dictionaryFor(scheme, accent, selector, cssFilter);
    const { allTokens } = await sd.getPlatformTokens('rn');
    colorsByCombo[`${scheme}/${accent}`] = toTree(allTokens, 'color');

    if (isDefault && scheme === 'light') {
      base = Object.fromEntries(
        [
          'spacing',
          'size',
          'breakpoint',
          'radius',
          'fontSize',
          'fontWeight',
          'lineHeight',
          'opacity',
          'shadow',
        ].map((k) => [k, toTree(allTokens, k)]),
      );
      palette = Object.fromEntries(
        ['ink', ...ACCENTS, 'status'].map((k) => [k, toTree(allTokens, k)]),
      );
    }

    const [css] = await sd.formatPlatform('css');
    cssBlocks.push(String(css.output).trim());
  }
}

// Accent overrides: only the keys that differ from the default accent (empty for the default).
const accentOverrides = {};
for (const accent of ACCENTS) {
  accentOverrides[accent] = {};
  for (const scheme of SCHEMES) {
    const full = colorsByCombo[`${scheme}/${accent}`];
    const def = colorsByCombo[`${scheme}/${DEFAULT_ACCENT}`];
    accentOverrides[accent][scheme] = Object.fromEntries(
      Object.entries(full).filter(([k, v]) => def[k] !== v),
    );
  }
}

const js = (value) => JSON.stringify(value, null, 2);
const files = {
  'base.ts': `${HEADER}\nexport const base = ${js(base)} as const;\n`,
  'palette.ts': `${HEADER}\n// Primitive colors, for the design system showcase only. Components use semantic tokens.\nexport const palette = ${js(palette)} as const;\n`,
  'light.ts': `${HEADER}\nexport const light = { scheme: 'light', color: ${js(colorsByCombo[`light/${DEFAULT_ACCENT}`])} } as const;\n`,
  'dark.ts': `${HEADER}\nexport const dark = { scheme: 'dark', color: ${js(colorsByCombo[`dark/${DEFAULT_ACCENT}`])} } as const;\n`,
  'accents.ts': `${HEADER}\nexport const accentNames = ${js(ACCENTS)} as const;\nexport type Accent = (typeof accentNames)[number];\nexport const defaultAccent: Accent = '${DEFAULT_ACCENT}';\n\n// Per accent and scheme, only the color tokens that differ from ${DEFAULT_ACCENT}.\nexport const accentOverrides = ${js(accentOverrides)} as const;\n`,
  'index.ts': `${HEADER}
import { dark } from './dark';
import { light } from './light';

import { type Accent, accentOverrides } from './accents';

export { accentNames, defaultAccent, type Accent } from './accents';
export { base } from './base';
export { dark } from './dark';
export { light } from './light';
export { palette } from './palette';

export type Scheme = 'light' | 'dark';
export type ColorTokens = { [K in keyof typeof light.color]: string };

// A key missing from dark (or light) is a compile error here.
export const schemes: Record<Scheme, { scheme: Scheme; color: ColorTokens }> = { light, dark };

// Every accent must cover both schemes and may only override real color tokens.
export const accentColorOverrides: Record<Accent, Record<Scheme, Partial<ColorTokens>>> = accentOverrides;
`,
};

await mkdir(OUT, { recursive: true });
const prettierConfig = (await prettier.resolveConfig(path.join(OUT, 'index.ts'))) ?? {};
for (const [name, source] of Object.entries(files)) {
  const formatted = await prettier.format(source, { ...prettierConfig, parser: 'typescript' });
  await writeFile(path.join(OUT, name), formatted);
}
const css = `/* Generated by scripts/build-tokens.mjs from tokens/. Do not edit by hand. */\n${cssBlocks.join('\n\n')}\n`;
await writeFile(
  path.join(OUT, 'tokens.css'),
  await prettier.format(css, { ...prettierConfig, parser: 'css' }),
);
await writeFile(path.join(OUT, 'themes.json'), `${js(colorsByCombo)}\n`);

console.log(
  `tokens: built ${Object.keys(files).length} TS files, tokens.css, themes.json → ${OUT}`,
);
