// `npm run tokens` (step 1 of 2): tokens/ (W3C DTCG JSON) → Style Dictionary →
//   src/design-system/tokens/generated/*.ts   typed React Native theme
//   src/design-system/tokens/generated/tokens.css   CSS variables for web, same source
//   src/design-system/tokens/generated/themes.json  light and dark colors, read by check-contrast
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

import * as prettier from 'prettier';
import StyleDictionary from 'style-dictionary';

const OUT = 'src/design-system/tokens/generated';
const SCHEMES = ['light', 'dark'];
const HEADER =
  '// Generated by scripts/build-tokens.mjs from tokens/. Do not edit by hand; run `npm run tokens`.\n';

const typeOf = (token) => token.$type ?? token.type;
const valueOf = (token) => token.$value ?? token.value;

// React Native transforms. RN sizes are unitless numbers, font weights are string literals,
// and RN 0.76+ (and react-native-web) take a CSS-style boxShadow string on every platform.
StyleDictionary.registerTransform({
  name: 'rn/dimension',
  type: 'value',
  filter: (token) => typeOf(token) === 'dimension',
  transform: (token) => parseFloat(String(valueOf(token))),
});
StyleDictionary.registerTransform({
  name: 'rn/fontWeight',
  type: 'value',
  filter: (token) => typeOf(token) === 'fontWeight',
  transform: (token) => String(valueOf(token)),
});
StyleDictionary.registerTransform({
  name: 'rn/shadow',
  type: 'value',
  filter: (token) => typeOf(token) === 'shadow',
  transform: (token) => {
    const { offsetX, offsetY, blur, spread, color } = valueOf(token);
    return `${offsetX} ${offsetY} ${blur} ${spread} ${color}`;
  },
});

function dictionaryFor(scheme, cssSelector, cssFilter) {
  return new StyleDictionary({
    source: ['tokens/primitive/*.json', `tokens/semantic/${scheme}.json`],
    usesDtcg: true,
    log: { verbosity: 'silent', warnings: 'disabled' },
    platforms: {
      rn: { transforms: ['rn/dimension', 'rn/fontWeight', 'rn/shadow'] },
      css: {
        transformGroup: 'css',
        prefix: 'dk',
        files: [
          {
            destination: 'tokens.css',
            format: 'css/variables',
            filter: cssFilter,
            options: { selector: cssSelector, outputReferences: false, showFileHeader: false },
          },
        ],
      },
    },
  });
}

/** Rebuild a nested plain object from Style Dictionary's flat token list. */
function toTree(allTokens, rootKey) {
  const tree = {};
  for (const token of allTokens) {
    if (token.path[0] !== rootKey) continue;
    let node = tree;
    const rest = token.path.slice(1);
    rest.forEach((key, i) => {
      if (i === rest.length - 1) node[key] = valueOf(token);
      else node = node[key] ??= {};
    });
  }
  return tree;
}

const colorsByScheme = {};
const cssBlocks = [];
let base;

for (const scheme of SCHEMES) {
  // :root carries everything; the dark block carries only the colors.
  const selector = scheme === 'light' ? ':root' : '[data-theme="dark"]';
  const cssFilter = scheme === 'light' ? undefined : (token) => token.path[0] === 'color';

  const sd = dictionaryFor(scheme, selector, cssFilter);
  const { allTokens } = await sd.getPlatformTokens('rn');
  colorsByScheme[scheme] = toTree(allTokens, 'color');

  if (scheme === 'light') {
    base = Object.fromEntries(
      [
        'spacing',
        'size',
        'breakpoint',
        'radius',
        'fontSize',
        'fontWeight',
        'lineHeight',
        'opacity',
        'shadow',
      ].map((k) => [k, toTree(allTokens, k)]),
    );
  }

  const [css] = await sd.formatPlatform('css');
  cssBlocks.push(String(css.output).trim());
}

const js = (value) => JSON.stringify(value, null, 2);
const files = {
  'base.ts': `${HEADER}\nexport const base = ${js(base)} as const;\n`,
  'light.ts': `${HEADER}\nexport const light = { scheme: 'light', color: ${js(colorsByScheme.light)} } as const;\n`,
  'dark.ts': `${HEADER}\nexport const dark = { scheme: 'dark', color: ${js(colorsByScheme.dark)} } as const;\n`,
  'index.ts': `${HEADER}
import { dark } from './dark';
import { light } from './light';

export { base } from './base';
export { dark } from './dark';
export { light } from './light';

export type Scheme = 'light' | 'dark';
export type ColorTokens = { [K in keyof typeof light.color]: string };

// A key missing from dark (or light) is a compile error here.
export const schemes: Record<Scheme, { scheme: Scheme; color: ColorTokens }> = { light, dark };
`,
};

await mkdir(OUT, { recursive: true });
const prettierConfig = (await prettier.resolveConfig(path.join(OUT, 'index.ts'))) ?? {};
for (const [name, source] of Object.entries(files)) {
  const formatted = await prettier.format(source, { ...prettierConfig, parser: 'typescript' });
  await writeFile(path.join(OUT, name), formatted);
}
const css = `/* Generated by scripts/build-tokens.mjs from tokens/. Do not edit by hand. */\n${cssBlocks.join('\n\n')}\n`;
await writeFile(
  path.join(OUT, 'tokens.css'),
  await prettier.format(css, { ...prettierConfig, parser: 'css' }),
);
await writeFile(path.join(OUT, 'themes.json'), `${js(colorsByScheme)}\n`);

console.log(
  `tokens: built ${Object.keys(files).length} TS files, tokens.css, themes.json → ${OUT}`,
);
